Iter15
Lesnoi3283/url_shortener pull request #15
Opened 2024-05-13 20:59 UTC by Lesnoi3283

2024-05-17 23:24 UTC, avhitrov requested changes
Предлагаю отрефакторить хранилища так, чтобы они имели один общий интерфейс и реализацию **каждой** функции (включая Ping). Если нужно пояснение, предлагаю встретиться и обсудить на 1-1.

2024-05-17 23:24 UTC, avhitrov commented on cmd/shortener/main.go
> +	//который должен пинговать именно постгрес (по требованию задания)
Если DBConnString пустой, то db по-любому будет nil и никакого Ping реализовать все равно не сможет. Правильнее будет построить единый интерфейс для всех стораджей, включающий, в том числе и функцию Ping. Просто для файлового и in-memory хранилищ сделать статичный вывод.

2024-06-04 21:25 UTC, avhitrov requested changes
Рефакторинг стораджей зачтен, мидлваре-ограничитель приятно удивила. Но по коду осталось какое-то количество мелких недоделок плюс обнаружились гонки в in-memory хранилище. Отметил в комментариях к коду.

2024-06-04 21:25 UTC, avhitrov commented on cmd/shortener/main.go
>  	}
Неиспользуемый блок. Инициализируется еще один экземпляр соединения с БД и потом просто закрывается. Надо убрать.

2024-06-04 21:25 UTC, avhitrov commented on internal/app/middlewares/auth_mw.go
> +//}
Весь этот фрагмент уже есть в системе хранения версий, не нужно его тащить в мастер и оставлять в коде.

2024-06-04 21:25 UTC, avhitrov commented on pkg/databases/just_a_map.go
> +	UserStore map[string]int
Я не вполне понял. Мьютекс потерялся или его тут и не было? А если не было, то как я его отсутствие мог пропустить?.. Думаю, нет смысла рассказывать про мапу и DATA RACE, подозреваю, что это просто было упущено при предыдущих проверках. В общем, в данном сторадже гонки. Если нужны подробности, они здесь: https://t.me/bushigo/24
```
==================
WARNING: DATA RACE
Read at 0x00c00003b5f0 by goroutine 24:
  runtime.mapaccess2_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:108 +0x0
  github.com/Lesnoi3283/url_shortener/pkg/databases.(*JustAMap).Get()
      C:/work/src/github.com/Lesnoi3283/url_shortener/pkg/databases/just_a_map.go:88 +0x64
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.(*ShortURLRedirectHandler).ServeHTTP()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/handlers/url_shortener_handler.go:41 +0x119
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.(*ShortURLRedirectHandler).ServeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436 +0x488
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.AuthMW.func4.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/auth_mw.go:96 +0x32b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.CompressionMW.func3.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/compression_mw.go:74 +0x272
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.RequestLimiterMW.func2.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/request_limiter_mw.go:98 +0x21c
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.LoggerMW.func1.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/logger_mw.go:43 +0x10b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87 +0x681
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous write at 0x00c00003b5f0 by goroutine 10:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  github.com/Lesnoi3283/url_shortener/pkg/databases.(*JustAMap).SaveWithUserID()
      C:/work/src/github.com/Lesnoi3283/url_shortener/pkg/databases/just_a_map.go:23 +0x73
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.(*URLShortenerHandler).ServeHTTP()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/handlers/url_shortener_handler.go:86 +0x36a
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.(*URLShortenerHandler).ServeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436 +0x488
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.AuthMW.func4.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/auth_mw.go:96 +0x32b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.CompressionMW.func3.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/compression_mw.go:74 +0x272
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.RequestLimiterMW.func2.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/request_limiter_mw.go:98 +0x21c
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/Lesnoi3283/url_shortener/internal/app/handlers.NewRouter.LoggerMW.func1.1()
      C:/work/src/github.com/Lesnoi3283/url_shortener/internal/app/middlewares/logger_mw.go:43 +0x10b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87 +0x681
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 24 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0xb4d
  main.main()
      C:/work/src/github.com/Lesnoi3283/url_shortener/cmd/shortener/main.go:59 +0x9d8

Goroutine 10 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0xb4d
  main.main()
      C:/work/src/github.com/Lesnoi3283/url_shortener/cmd/shortener/main.go:59 +0x9d8
==================
```

2024-06-05 09:44 UTC, Lesnoi3283 commented on internal/app/middlewares/auth_mw.go
> +//}
Забыл убрать, обычно такое не оставляю)

2024-06-06 14:15 UTC, Lesnoi3283 commented on cmd/shortener/main.go
>  	}
fix

2024-06-06 14:15 UTC, Lesnoi3283 commented on internal/app/middlewares/auth_mw.go
> +//}
done

2024-06-06 14:15 UTC, Lesnoi3283 commented on pkg/databases/just_a_map.go
> +	UserStore map[string]int
done

2024-06-09 22:41 UTC, avhitrov approved these changes
Все отлично.

2024-06-10 05:15 UTC, merged