Revert "Revert "Iter18""
Lesnoi3283/url_shortener pull request #19
Opened 2024-10-08 21:40 UTC by Lesnoi3283

2024-10-10 17:13 UTC, nburunova commented
бинари и репорты от оптимизации обычно не кладут в репозиторий internal/app/handlers/memAfterOptimisation.out , можно какой-то readme написать с описаниями оптимизаций, чтобы другие разработчики были в курсе. Но именно сами бинарные и репорты не стоит класть. Иначе если другой разработчик прогонит тесты, у него поменяются бинари, ему дифф в реп пушить? Это не та информация, о которой нужно следить через гит (контроль версий)

2024-10-10 17:26 UTC, nburunova requested changes

2024-10-10 17:26 UTC, nburunova commented on internal/app/handlers/delete_urls_handler.go
> +		//res.WriteHeader(http.StatusInternalServerError)
закомментированный код нужно урбать, так репозиторий будет выглядеть аккуратнее

2024-10-10 17:26 UTC, nburunova commented on internal/app/handlers/router_builders.go
> +	//requestManager := middlewares.NewRequestManager(100, time.Minute)
удалить неиспользуемый код

2024-10-10 17:26 UTC, nburunova commented on internal/app/handlers/shortenFunc.go
> +func ShortenURL(url []byte) []byte {
не обязательно делать эту фукнцию публичной, как я понимаю, она нужна только внутри пакета handlers

2024-10-10 17:26 UTC, nburunova commented on internal/app/handlers/shorten_batch_handler.go
> +	//URLsToReturn := make([]URLShorten, 0)
переменные в го приято называть с маленькой буквы urlsToSave

2024-10-10 17:26 UTC, nburunova commented on internal/app/handlers/url_shortener_handler.go
> +// URLStorageInterface is a main database interface.
minor : в го не принятно в названиях интерфейсов употреблять слова Interface , I и тд. Обычно в названиях интерфейсов используется суффикc -er, посмотри как в библиотеках Го называются интерфейсы, это обычно Reader, Closer и тд

2024-10-15 18:03 UTC, Lesnoi3283 commented on internal/app/handlers/delete_urls_handler.go
> +		//res.WriteHeader(http.StatusInternalServerError)
done

2024-10-15 18:04 UTC, Lesnoi3283 commented on internal/app/handlers/router_builders.go
> +	//requestManager := middlewares.NewRequestManager(100, time.Minute)
done

2024-10-15 18:05 UTC, Lesnoi3283 commented on internal/app/handlers/shorten_batch_handler.go
> +	//URLsToReturn := make([]URLShorten, 0)
done

2024-10-15 18:13 UTC, Lesnoi3283 commented on internal/app/handlers/shorten_batch_handler.go
> +	//URLsToReturn := make([]URLShorten, 0)
done

2024-10-15 18:14 UTC, Lesnoi3283 commented on internal/app/handlers/shortenFunc.go
> +func ShortenURL(url []byte) []byte {
ok

2024-10-15 18:19 UTC, Lesnoi3283 commented on internal/app/handlers/url_shortener_handler.go
> +// URLStorageInterface is a main database interface.
Да, в теории курсов это было, но в данном случае трудно подобрать такое слово с окончанием -er, чтобы было понятно что интерфейс описывает. В этом случае разрешено добавлять слово Interface. Другой вариант - разбить интерфейс на составляющие и назвать "urlSaver", "userURLSaver", "pinger" и т.д., но предыдущий ментор сказал что в небольших проектах, по типу этого, это не имеет смысла и лишь усложняет код.

2024-10-16 10:41 UTC, nburunova approved these changes

2024-10-16 12:54 UTC, merged